2023-12-02 13:06:35,783 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Configure stats pid to 9096
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/.config/wandb/settings
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/Thesis/baselines/SCRIMP/wandb/settings
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-02 13:06:35,784 INFO    MainThread:9096 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'eval_model.py', 'program_abspath': '/home/andrea/Thesis/baselines/SCRIMP/eval_model.py', 'program': 'eval_model.py'}
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:_log_setup():524] Logging user logs to /home/andrea/Thesis/baselines/SCRIMP/wandb/run-20231202_130635-xiuuv46a/logs/debug.log
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:_log_setup():525] Logging internal logs to /home/andrea/Thesis/baselines/SCRIMP/wandb/run-20231202_130635-xiuuv46a/logs/debug-internal.log
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:init():564] calling init triggers
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:init():572] wandb.init called with sweep_config: {}
config: {'N_AGENTS': 8, 'N_ACTIONS': 5, 'EPISODE_LEN': 256, 'FOV_SIZE': 3, 'WORLD_SIZE': (10, 40), 'OBSTACLE_PROB': (0.0, 0.5), 'ACTION_COST': -0.3, 'IDLE_COST': -0.3, 'GOAL_REWARD': 0.0, 'COLLISION_COST': -2, 'BLOCKING_COST': -1, 'lr': 1e-05, 'GAMMA': 0.95, 'LAM': 0.95, 'CLIPRANGE': 0.2, 'MAX_GRAD_NORM': 10, 'ENTROPY_COEF': 0.01, 'IN_VALUE_COEF': 0.08, 'EX_VALUE_COEF': 0.08, 'POLICY_COEF': 10, 'VALID_COEF': 0.5, 'BLOCK_COEF': 0.5, 'N_EPOCHS': 10, 'N_ENVS': 16, 'N_MAX_STEPS': 30000000.0, 'N_STEPS': 1024, 'MINIBATCH_SIZE': 1024, 'DEMONSTRATION_PROB': 0.1, 'NET_SIZE': 512, 'NUM_CHANNEL': 8, 'GOAL_REPR_SIZE': 12, 'VECTOR_LEN': 7, 'N_POSITION': 1024, 'D_MODEL': 512, 'D_HIDDEN': 1024, 'N_LAYERS': 1, 'N_HEAD': 8, 'D_K': 32, 'D_V': 32, 'DIST_FACTOR': 0.1, 'K': 3, 'CAPACITY': 80, 'ADD_THRESHOLD': 3, 'N_ADD_INTRINSIC': 1000000.0, 'SURROGATE1': 0.2, 'SURROGATE2': 1, 'SEED': 1234, 'USE_GPU_LOCAL': False, 'USE_GPU_GLOBAL': True, 'NUM_GPU': 1, 'RETRAIN': False, 'WANDB': True, 'TENSORBOARD': True, 'TXT_WRITER': True, 'ENTITY': 'yutong', 'TIME': '02-12-231306', 'EXPERIMENT_PROJECT': 'MAPF', 'EXPERIMENT_NAME': 'SCRIMP', 'EXPERIMENT_NOTE': '', 'SAVE_INTERVAL': 500000.0, 'BEST_INTERVAL': 0, 'GIF_INTERVAL': 1000000.0, 'EVAL_INTERVAL': 16384, 'EVAL_EPISODES': 1, 'RECORD_BEST': False, 'MODEL_PATH': './models/MAPF/SCRIMP02-12-231306', 'GIFS_PATH': './gifs/MAPF/SCRIMP02-12-231306', 'SUMMARY_PATH': './summaries/MAPF/SCRIMP02-12-231306', 'TXT_NAME': 'alg.txt'}
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:init():614] starting backend
2023-12-02 13:06:35,785 INFO    MainThread:9096 [wandb_init.py:init():618] setting up manager
2023-12-02 13:06:35,796 INFO    MainThread:9096 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-02 13:06:35,799 INFO    MainThread:9096 [wandb_init.py:init():624] backend started and connected
2023-12-02 13:06:35,829 INFO    MainThread:9096 [wandb_init.py:init():716] updated telemetry
2023-12-02 13:06:35,935 INFO    MainThread:9096 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-02 13:06:36,704 ERROR   MainThread:9096 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-02 13:06:36,911 ERROR   MainThread:9096 [wandb_init.py:init():1184] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/SCRIMP-env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/home/andrea/miniconda3/envs/SCRIMP-env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-02 13:06:37,917 WARNING MsgRouterThr:9096 [router.py:message_loop():77] message_loop has been closed
